<?php

return [
    'AED' => 'د.إ',    // UAE Dirham
    'AFN' => '؋',      // Afghan Afghani
    'ALL' => 'L',      // Albanian Lek
    'AMD' => '֏',      // Armenian Dram
    'ANG' => 'ƒ',      // Netherlands Antillean Guilder
    'AOA' => 'Kz',     // Angolan Kwanza
    'ARS' => 'AR$',    // Argentine Peso
    'AUD' => 'A$',     // Australian Dollar
    'AWG' => 'ƒ',      // Aruban Florin
    'AZN' => '₼',      // Azerbaijani Manat
    'BAM' => 'KM',     // Bosnia-Herzegovina Convertible Mark
    'BBD' => 'Bds$',   // Barbadian Dollar
    'BDT' => '৳',      // Bangladeshi Taka
    'BGN' => 'лв',     // Bulgarian Lev
    'BHD' => '.د.ب',   // Bahraini Dinar
    'BIF' => 'FBu',    // Burundian Franc
    'BMD' => 'BD$',    // Bermudian Dollar
    'BND' => 'B$',     // Brunei Dollar
    'BOB' => 'Bs.',    // Bolivian Boliviano
    'BRL' => 'R$',     // Brazilian Real
    'BSD' => 'B$',     // Bahamian Dollar
    'BTN' => 'Nu.',    // Bhutanese Ngultrum
    'BWP' => 'P',      // Botswana Pula
    'BYN' => 'Br',     // Belarusian Ruble
    'BZD' => 'BZ$',    // Belize Dollar
    'CAD' => 'C$',     // Canadian Dollar
    'CDF' => 'FC',     // Congolese Franc
    'CHF' => 'CHF',    // Swiss Franc
    'CLP' => 'CLP$',   // Chilean Peso
    'CNY' => '¥',      // Chinese Yuan
    'COP' => 'COL$',   // Colombian Peso
    'CRC' => '₡',      // Costa Rican Colón
    'CUP' => '₱',      // Cuban Peso
    'CVE' => 'Esc',    // Cape Verdean Escudo
    'CZK' => 'Kč',     // Czech Koruna
    'DJF' => 'Fdj',    // Djiboutian Franc
    'DKK' => 'kr',     // Danish Krone
    'DOP' => 'RD$',    // Dominican Peso
    'DZD' => 'د.ج',   // Algerian Dinar
    'EGP' => 'E£',     // Egyptian Pound
    'ERN' => 'Nfk',    // Eritrean Nakfa
    'ETB' => 'Br',     // Ethiopian Birr
    'EUR' => '€',      // Euro
    'FJD' => 'FJ$',    // Fijian Dollar
    'FKP' => '£',      // Falkland Islands Pound
    'FOK' => 'kr',     // Faroese Króna
    'GBP' => '£',      // British Pound
    'GEL' => '₾',      // Georgian Lari
    'GHS' => 'GH₵',    // Ghanaian Cedi
    'GIP' => '£',      // Gibraltar Pound
    'GMD' => 'D',      // Gambian Dalasi
    'GNF' => 'FG',     // Guinean Franc
    'GTQ' => 'Q',      // Guatemalan Quetzal
    'GYD' => 'G$',     // Guyanese Dollar
    'HKD' => 'HK$',    // Hong Kong Dollar
    'HNL' => 'L',      // Honduran Lempira
    'HRK' => 'kn',     // Croatian Kuna
    'HTG' => 'G',      // Haitian Gourde
    'HUF' => 'Ft',     // Hungarian Forint
    'IDR' => 'Rp',     // Indonesian Rupiah
    'ILS' => '₪',      // Israeli Shekel
    'INR' => '₹',      // Indian Rupee
    'IQD' => 'ع.د',   // Iraqi Dinar
    'IRR' => '﷼',     // Iranian Rial
    'ISK' => 'kr',     // Icelandic Króna
    'JMD' => 'J$',     // Jamaican Dollar
    'JOD' => 'د.ا',   // Jordanian Dinar
    'JPY' => '¥',      // Japanese Yen
    'KES' => 'KSh',    // Kenyan Shilling
    'KGS' => 'сом',    // Kyrgyzstani Som
    'KHR' => '៛',      // Cambodian Riel
    'KMF' => 'CF',     // Comorian Franc
    'KRW' => '₩',      // South Korean Won
    'KWD' => 'د.ك',   // Kuwaiti Dinar
    'KZT' => '₸',      // Kazakhstani Tenge
    'LAK' => '₭',      // Lao Kip
    'LBP' => 'ل.ل',   // Lebanese Pound
    'LKR' => 'Rs',     // Sri Lankan Rupee
    'LRD' => 'L$',     // Liberian Dollar
    'LYD' => 'ل.د',   // Libyan Dinar
    'MAD' => 'DH',     // Moroccan Dirham
    'MDL' => 'L',      // Moldovan Leu
    'MGA' => 'Ar',     // Malagasy Ariary
    'MKD' => 'ден',    // Macedonian Denar
    'MMK' => 'K',      // Myanmar Kyat
    'MNT' => '₮',      // Mongolian Tögrög
    'MOP' => 'MOP$',   // Macanese Pataca
    'MUR' => '₨',      // Mauritian Rupee
    'MVR' => 'Rf',     // Maldivian Rufiyaa
    'MWK' => 'MK',     // Malawian Kwacha
    'MXN' => 'Mex$',   // Mexican Peso
    'MYR' => 'RM',     // Malaysian Ringgit
    'MZN' => 'MT',     // Mozambican Metical
    'NAD' => 'N$',     // Namibian Dollar
    'NGN' => '₦',      // Nigerian Naira
    'NOK' => 'kr',     // Norwegian Krone
    'NPR' => 'Rs',     // Nepalese Rupee
    'NZD' => 'NZ$',    // New Zealand Dollar
    'OMR' => 'ر.ع.',  // Omani Rial
    'PEN' => 'S/',     // Peruvian Sol
    'PGK' => 'K',      // Papua New Guinean Kina
    'PHP' => '₱',      // Philippine Peso
    'PKR' => '₨',      // Pakistani Rupee
    'PLN' => 'zł',     // Polish Złoty
    'QAR' => 'ر.ق',   // Qatari Riyal
    'RON' => 'lei',    // Romanian Leu
    'RUB' => '₽',      // Russian Ruble
    'SAR' => '﷼',     // Saudi Riyal
    'SEK' => 'kr',     // Swedish Krona
    'SGD' => 'S$',     // Singapore Dollar
    'THB' => '฿',      // Thai Baht
    'TRY' => '₺',      // Turkish Lira
    'USD' => '$',      // United States Dollar
    'VND' => '₫',      // Vietnamese Dong
    'ZAR' => 'R',      // South African Rand
];

